### ISSUE TITLE
TDV's Strange Problem with Windows 10 X64

### ISSUE THREAD

**Issue by sshubhamm** [munawarb/Three-D-Velocity#29]
Hello @munawarb,
Three-D-Velocity is not working in my Windows 10 X64 system. The introduction message of the game is playing properly, however, as main menu about to appear, the game crashes and a Windows dialog box poppes up asking whether I let Windows to find a solution about this prroblem for me. It still even doesn't work after applying several different settings of Windows Troubleshooter to it.
I want to let you know that I've installed all the required components for the game to work as described at the homepage of TDV.
System:  Windows 10 Pro X64 (Anniversary Edition)

**Comment by munawarb** [comment]
Hi @sshubhamm,
Are you running the Master branch or Release branch of TDV?

**Comment by munawarb** [comment]
Hi @sshubhamm,
I've pushed a possible fix to this issue which was also mentioned in #30. Are you still having this problem after downloading the latest binary release? I wasn't able to reproduce the problem so please verify that it has or has not been resolved.

**Comment by sshubhamm** [comment]
Thanks @munawarb for your effort to resolve the problem. I'll check and update the details as earliest. But I'm wondering, why it took so long for you to fix the issue?

**Comment by munawarb** [comment]
My apologies for any inconvenience you experienced while waiting.

Please let me know if your issue is solved or if I need to look into it further.

**Comment by munawarb** [comment]
Fixed in #30

**Comment by blindpilot** [comment]
Munawar, please remind me how we can down load and install TDV once again please.
Also, anyone have a USB handheld device with two stick or I was told that a x-box 360 handheld device is suppose to have two sticks on it. But could we plug that unit into a USB to take over TDV with?
Also, let not forget a set of USB rudder Peddles to make TDV even closer to the real world.
That’s if TDV would work with a set of USB rudder Peddles?
It’s sad but true, TDV is to my knowledge the only hand to ear project that even today had force feedback written into the program.
I spend from February 23rd until April 29th in a nursing home for OT and PT because on February the 18th, I tripped over something that was suppose to be picked up and wasn’t and I tripped over it braking most of the bones in my right wrist.
Then I had surgery on the wrist on February 23rd and spent the the weekend in the hospital until we could go through the red tape to get into the nursing home on Monday the 26.
So I now have a titanium plate in my right wrist connecting my hand to my arm. 
So, I’m also trying to play catch up as well. 
Many thanks from a old TDV beta tester when we had force feedback with the 32 bit processors.
Ron Kolesar AKA The Blind Pilot in the flight sim world and U.S. ham radio station KR3DOG-PA-WCECTM in the real world.

**Comment by munawarb** [comment]
Hi @blindpilot,
Please download from this link, as stated on the main page: https://github.com/munawarb/Three-D-Velocity-Binaries/archive/master.zip

The `tdv.exe` executable is in there.

That's terrible what you've been through lately, I was wondering where you've gone off to!

Remember that Github is public, so you might want to edit your comment to remove all of your personal medical happenings. You don't have to, but I thought I'd let you know so there are no surprises later on. Just because this issue is closed doesn't mean it's no longer viewable.

**Comment by CronoMaxwell** [comment]
Hey @blindpilot  hope you get better in time man have an nice day.

**Comment by blindpilot** [comment]
Many thanks for the best whishes. 
I see the surgeon, probably for the last time on the 21st. 
I still have issues with the wrist and the thumb area. 
But I’m doing my exercises for those areas though. 
Many thanks.
Ron AKA in flying circles known as the blind pilot and in the real world known as Amateur Radio Station KR3DOG-PA-WCECTM
Who hates emergency weather drills, but that’s what keeps us on our toes. SMILES. 
Ron who’s looking for a two stick handheld unit to fly TDV via hand to ear and hopefully can find something that will support the force feedback feature in the 64 bit world, like we enjoyed in the days of the 32 bit processor world. 
Ron
